DROP TABLE IF EXISTS usuarios;
CREATE TABLE usuarios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre_completo VARCHAR(255) NOT NULL UNIQUE,
  cedula INTEGER NOT NULL UNIQUE,
  usuario VARCHAR(255) NOT NULL UNIQUE,
  contrasena VARCHAR(255) NOT NULL,
  rol VARCHAR(1) NOT NULL CHECK (rol IN ('A', 'U'))
);
